const STATUSES = new Set(["TO DO","EXECUTING","PASSED","FAILED","BLOCKED","ABORTED"]);
const json = (data, status=200, extra={}) => new Response(JSON.stringify(data), {status, headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store",...extra}});
const uid = () => crypto.randomUUID();
const iso = () => new Date().toISOString();
const body = async req => { try { return await req.json(); } catch { throw new Error("Ungültige JSON-Daten"); } };
const cleanStatus = value => { const v=String(value||"TO DO").toUpperCase(); if(!STATUSES.has(v)) throw new Error("Ungültiger Status"); return v; };

const enc = new TextEncoder();
const bytes64 = bytes => btoa(String.fromCharCode(...new Uint8Array(bytes)));
const randomToken = (size=32) => { const b=new Uint8Array(size); crypto.getRandomValues(b); return bytes64(b).replaceAll("+","-").replaceAll("/","_").replaceAll("=",""); };
const digest = async value => bytes64(await crypto.subtle.digest("SHA-256",enc.encode(value)));
async function passwordHash(password,salt,iterations=100000){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);return bytes64(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:enc.encode(salt),iterations},key,256));}
function cookie(req,name){const raw=req.headers.get("cookie")||"";for(const part of raw.split(";")){const [k,...v]=part.trim().split("=");if(k===name)return decodeURIComponent(v.join("="));}return "";}
async function currentUser(req,db){const token=cookie(req,"rd_session");if(!token)return null;const hash=await digest(token);return db.prepare("SELECT u.id,u.email,u.display_name FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?").bind(hash,iso()).first();}
async function createSession(db,userId){const token=randomToken(),at=iso(),expires=new Date(Date.now()+7*86400000).toISOString();await db.prepare("INSERT INTO sessions (id,user_id,token_hash,expires_at,created_at) VALUES (?,?,?,?,?)").bind(uid(),userId,await digest(token),expires,at).run();return {token,expires};}
const sessionCookie=(token,maxAge=604800)=>`rd_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;

async function audit(db, releaseId, test, field, oldValue, newValue, note="", actor="") {
  await db.prepare("INSERT INTO audit_log (id,release_id,test_case_id,test_key,field,old_value,new_value,note,actor,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)")
    .bind(uid(),releaseId,test?.id||null,test?.test_key||"",field,String(oldValue??""),String(newValue??""),note,actor,iso()).run();
}
async function getRelease(db,id,userId){
  const release=await db.prepare("SELECT * FROM releases WHERE id=? AND user_id=?").bind(id,userId).first(); if(!release)return null;
  const cases=(await db.prepare("SELECT * FROM test_cases WHERE release_id=? ORDER BY test_key").bind(id).all()).results;
  const steps=(await db.prepare("SELECT s.* FROM test_steps s JOIN test_cases t ON t.id=s.test_case_id WHERE t.release_id=? ORDER BY s.test_case_id,s.step_no").bind(id).all()).results;
  const byCase=new Map();steps.forEach(s=>{if(!byCase.has(s.test_case_id))byCase.set(s.test_case_id,[]);byCase.get(s.test_case_id).push(s)});
  const defects=(await db.prepare("SELECT * FROM defects WHERE release_id=? ORDER BY created_at DESC").bind(id).all()).results;
  const evidence=(await db.prepare("SELECT id,release_id,test_case_id,test_step_id,file_name,mime_type,file_size,note,created_at FROM evidence WHERE release_id=? ORDER BY created_at DESC").bind(id).all()).results;
  const preconditions=(await db.prepare("SELECT x.test_case_id,p.id,p.precondition_key,p.name,p.condition_text,p.status FROM test_case_preconditions x JOIN preconditions p ON p.id=x.precondition_id JOIN test_cases t ON t.id=x.test_case_id WHERE t.release_id=? ORDER BY p.precondition_key").bind(id).all()).results;
  const testSets=(await db.prepare("SELECT x.test_case_id,s.id,s.set_key,s.name,s.status FROM test_set_tests x JOIN test_sets s ON s.id=x.test_set_id JOIN test_cases t ON t.id=x.test_case_id WHERE t.release_id=? ORDER BY s.set_key").bind(id).all()).results;
  cases.forEach(t=>{t.steps=byCase.get(t.id)||[];t.defects=defects.filter(d=>d.test_case_id===t.id);t.evidence=evidence.filter(e=>e.test_case_id===t.id&&!e.test_step_id);t.preconditions=preconditions.filter(p=>p.test_case_id===t.id);t.test_sets=testSets.filter(s=>s.test_case_id===t.id);t.steps.forEach(s=>s.evidence=evidence.filter(e=>e.test_step_id===s.id));});
  return {...release,tests:cases,defects};
}
async function importTests(db,releaseId,payload,userId){
  const release=await db.prepare("SELECT * FROM releases WHERE id=? AND user_id=?").bind(releaseId,userId).first();if(!release)return json({error:"Release nicht gefunden"},404);
  const tests=Array.isArray(payload.tests)?payload.tests:[];if(!tests.length)return json({error:"Keine Testfälle übermittelt"},400);
  const at=iso();let created=0,updated=0;
  for(const raw of tests){
    const key=String(raw.key||raw.test_key||"").trim();if(!key)continue;
    const status=cleanStatus(raw.status||raw.local_status),existing=await db.prepare("SELECT * FROM test_cases WHERE release_id=? AND test_key=?").bind(releaseId,key).first();
    let id;
    if(existing){id=existing.id;const localChanged=existing.local_status!==existing.original_status;await db.prepare("UPDATE test_cases SET summary=?,test_type=?,workflow_status=?,original_status=?,local_status=?,sync_status=?,updated_at=? WHERE id=?").bind(String(raw.summary||existing.summary).trim(),raw.testType||raw.test_type||existing.test_type,raw.workflowStatus||raw.workflow_status||existing.workflow_status,status,localChanged?existing.local_status:status,localChanged?"CHANGED":"UNCHANGED",at,id).run();updated++;}
    else{id=uid();await db.prepare("INSERT INTO test_cases (id,release_id,test_key,summary,test_type,workflow_status,original_status,local_status,sync_status,tester,comment,actual_result,defect,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,releaseId,key,String(raw.summary||"").trim(),raw.testType||raw.test_type||"Manual",raw.workflowStatus||raw.workflow_status||"",status,status,"UNCHANGED",raw.tester||"",raw.comment||"",raw.actualResult||raw.actual_result||"",raw.defect||"",at).run();created++;}
    for(const [i,s] of (raw.steps||[]).entries()){const n=Number(s.number||s.step_no||i+1),step=await db.prepare("SELECT id,actual_result,status,comment FROM test_steps WHERE test_case_id=? AND step_no=?").bind(id,n).first(),stepStatus=cleanStatus(s.status||s.step_status||"TO DO"),actual=s.actualResult??s.actual_result,comment=s.comment??s.step_comment;if(step)await db.prepare("UPDATE test_steps SET action=?,test_data=?,expected_result=?,actual_result=?,status=?,comment=? WHERE id=?").bind(s.action||"",s.data||s.test_data||"",s.expectedResult||s.expected_result||"",actual??step.actual_result,stepStatus,comment??step.comment,step.id).run();else await db.prepare("INSERT INTO test_steps (id,test_case_id,step_no,action,test_data,expected_result,actual_result,status,comment) VALUES (?,?,?,?,?,?,?,?,?)").bind(uid(),id,n,s.action||"",s.data||s.test_data||"",s.expectedResult||s.expected_result||"",actual||"",stepStatus,comment||"").run();}
  }
  await db.prepare("UPDATE releases SET source_name=?,updated_at=? WHERE id=?").bind(payload.sourceName||"Xray CSV",at,releaseId).run();
  await audit(db,releaseId,null,"CSV-Import","",created+" erstellt, "+updated+" aktualisiert",payload.sourceName||"");
  return json(await getRelease(db,releaseId,userId));
}

async function listReusableTests(db,userId,targetReleaseId){
  const target=await db.prepare("SELECT id,name,execution_key FROM releases WHERE id=? AND user_id=?").bind(targetReleaseId,userId).first();
  if(!target)return null;
  const rows=(await db.prepare("SELECT t.id,t.test_key,t.summary,t.test_type,t.workflow_status,t.priority,t.folder_path,t.updated_at,r.id source_release_id,r.name source_release_name,r.execution_key source_execution_key,(SELECT COUNT(*) FROM test_steps s WHERE s.test_case_id=t.id) step_count FROM test_cases t JOIN releases r ON r.id=t.release_id WHERE r.user_id=? ORDER BY t.updated_at DESC,t.test_key").bind(userId).all()).results;
  const assigned=(await db.prepare("SELECT test_key FROM test_cases WHERE release_id=?").bind(targetReleaseId).all()).results;
  const assignedKeys=new Set(assigned.map(x=>String(x.test_key).toUpperCase())),seen=new Set(),tests=[];
  for(const row of rows){const key=String(row.test_key).toUpperCase();if(seen.has(key))continue;seen.add(key);tests.push({...row,already_assigned:assignedKeys.has(key)});}
  return {target,tests};
}
async function addExistingTests(db,userId,targetReleaseId,testIds,actor){
  const target=await db.prepare("SELECT id FROM releases WHERE id=? AND user_id=?").bind(targetReleaseId,userId).first();
  if(!target)throw Error("Testdurchführung nicht gefunden");
  const ids=[...new Set((Array.isArray(testIds)?testIds:[]).map(String).filter(Boolean))];
  if(!ids.length)throw Error("Mindestens einen Testfall auswählen");
  if(ids.length>500)throw Error("Pro Vorgang können höchstens 500 Testfälle hinzugefügt werden");
  let added=0,skipped=0;
  for(const sourceId of ids){
    const source=await db.prepare("SELECT t.* FROM test_cases t JOIN releases r ON r.id=t.release_id WHERE t.id=? AND r.user_id=?").bind(sourceId,userId).first();
    if(!source){skipped++;continue}
    const duplicate=await db.prepare("SELECT id FROM test_cases WHERE release_id=? AND UPPER(test_key)=UPPER(?)").bind(targetReleaseId,source.test_key).first();
    if(duplicate){skipped++;continue}
    const steps=(await db.prepare("SELECT * FROM test_steps WHERE test_case_id=? ORDER BY step_no").bind(source.id).all()).results;
    const preconditions=(await db.prepare("SELECT precondition_id FROM test_case_preconditions WHERE test_case_id=?").bind(source.id).all()).results;
    const testSets=(await db.prepare("SELECT test_set_id FROM test_set_tests WHERE test_case_id=?").bind(source.id).all()).results;
    const id=uid(),at=iso(),statements=[
      db.prepare("INSERT INTO test_cases (id,release_id,test_key,summary,test_type,workflow_status,original_status,local_status,sync_status,tester,comment,actual_result,defect,updated_at,precondition,requirement_key,labels,component,priority,folder_path) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,targetReleaseId,String(source.test_key||"").toUpperCase(),source.summary||"",source.test_type||"Manual",source.workflow_status||"READY","TO DO","TO DO","UNCHANGED","","","","",at,source.precondition||"",source.requirement_key||"",source.labels||"",source.component||"",source.priority||"Medium",source.folder_path||"")
    ];
    for(const step of steps)statements.push(db.prepare("INSERT INTO test_steps (id,test_case_id,step_no,action,test_data,expected_result,actual_result,status,comment) VALUES (?,?,?,?,?,?,?,?,?)").bind(uid(),id,Number(step.step_no||1),step.action||"",step.test_data||"",step.expected_result||"","","TO DO",""));
    for(const item of preconditions)statements.push(db.prepare("INSERT OR IGNORE INTO test_case_preconditions (test_case_id,precondition_id,created_at) VALUES (?,?,?)").bind(id,item.precondition_id,at));
    for(const item of testSets)statements.push(db.prepare("INSERT OR IGNORE INTO test_set_tests (test_set_id,test_case_id,created_at) VALUES (?,?,?)").bind(item.test_set_id,id,at));
    await db.batch(statements);
    await audit(db,targetReleaseId,{id,test_key:source.test_key},"Testfall","","Aus Repository hinzugefügt","Bestehender Testfall",actor||"");
    added++;
  }
  return {added,skipped,release:await getRelease(db,targetReleaseId,userId)};
}

async function api(req,env){
  const url=new URL(req.url),parts=url.pathname.split("/").filter(Boolean),method=req.method;
  try{
    if(url.pathname==="/api/health")return json({ok:true,service:"Mini Xray ReleaseDesk",time:iso()});
    if(url.pathname==="/api/auth/register"&&method==="POST"){const p=await body(req),email=String(p.email||"").trim().toLowerCase(),name=String(p.name||"").trim(),password=String(p.password||"");if(!/^[^ @]+@[^ @]+[.][^ @]+$/.test(email))return json({error:"Gültige E-Mail-Adresse erforderlich"},400);if(name.length<2)return json({error:"Name ist erforderlich"},400);if(password.length<10||!/[a-z]/.test(password)||!/[A-Z]/.test(password)||!/[0-9]/.test(password))return json({error:"Passwort benötigt mindestens 10 Zeichen, Gross- und Kleinbuchstaben sowie eine Zahl"},400);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"E-Mail-Adresse ist bereits registriert"},409);const id=uid(),salt=randomToken(18),at=iso(),iterations=100000,hash=await passwordHash(password,salt,iterations);await env.DB.prepare("INSERT INTO users (id,email,display_name,password_hash,password_salt,password_iterations,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,email,name,hash,salt,iterations,at,at).run();const s=await createSession(env.DB,id);return json({user:{id,email,display_name:name}},201,{"set-cookie":sessionCookie(s.token)});
    }
    if(url.pathname==="/api/auth/login"&&method==="POST"){const p=await body(req),email=String(p.email||"").trim().toLowerCase(),password=String(p.password||""),u=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!u||await passwordHash(password,u.password_salt,u.password_iterations)!==u.password_hash)return json({error:"E-Mail-Adresse oder Passwort ist falsch"},401);await env.DB.prepare("DELETE FROM sessions WHERE user_id=? AND expires_at<=?").bind(u.id,iso()).run();const s=await createSession(env.DB,u.id);return json({user:{id:u.id,email:u.email,display_name:u.display_name}},200,{"set-cookie":sessionCookie(s.token)});
    }
    if(url.pathname==="/api/auth/logout"&&method==="POST"){const token=cookie(req,"rd_session");if(token)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await digest(token)).run();return json({ok:true},200,{"set-cookie":sessionCookie("",0)});}
    const user=await currentUser(req,env.DB);
    if(url.pathname==="/api/auth/me")return user?json({user}):json({error:"Nicht angemeldet"},401);
    if(!user)return json({error:"Nicht angemeldet"},401);
    if(url.pathname==="/api/test-library"&&method==="GET"){const data=await listReusableTests(env.DB,user.id,String(url.searchParams.get("targetReleaseId")||""));return data?json(data):json({error:"Testdurchführung nicht gefunden"},404);}
    if(url.pathname==="/api/test-catalog"&&method==="GET")return json((await env.DB.prepare("SELECT t.id,t.test_key,t.summary,t.test_type,t.workflow_status,t.priority,t.folder_path,t.local_status,t.original_status,t.sync_status,t.tester,t.updated_at,r.id source_release_id,r.name source_release_name,r.execution_key source_execution_key,(SELECT COUNT(*) FROM test_steps s WHERE s.test_case_id=t.id) step_count FROM test_cases t JOIN releases r ON r.id=t.release_id WHERE r.user_id=? ORDER BY t.test_key COLLATE NOCASE,r.updated_at DESC").bind(user.id).all()).results);
    if(url.pathname==="/api/preconditions"&&method==="GET")return json((await env.DB.prepare("SELECT p.*, (SELECT COUNT(*) FROM test_case_preconditions x WHERE x.precondition_id=p.id) test_count FROM preconditions p WHERE user_id=? ORDER BY updated_at DESC").bind(user.id).all()).results);
    if(url.pathname==="/api/preconditions"&&method==="POST"){const p=await body(req),id=uid(),at=iso(),key=String(p.key||"").trim().toUpperCase(),name=String(p.name||"").trim();if(!key||!name)return json({error:"Precondition-Key und Name sind erforderlich"},400);await env.DB.prepare("INSERT INTO preconditions (id,user_id,precondition_key,name,condition_text,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,user.id,key,name,p.condition||"",p.status||"ACTIVE",at,at).run();return json(await env.DB.prepare("SELECT * FROM preconditions WHERE id=?").bind(id).first(),201);}
    if(parts[1]==="preconditions"&&parts[2]){const id=parts[2],item=await env.DB.prepare("SELECT * FROM preconditions WHERE id=? AND user_id=?").bind(id,user.id).first();if(!item)return json({error:"Precondition nicht gefunden"},404);if(method==="PATCH"){const p=await body(req);await env.DB.prepare("UPDATE preconditions SET precondition_key=?,name=?,condition_text=?,status=?,updated_at=? WHERE id=?").bind(String(p.key??item.precondition_key).toUpperCase(),p.name??item.name,p.condition??item.condition_text,p.status??item.status,iso(),id).run();return json(await env.DB.prepare("SELECT * FROM preconditions WHERE id=?").bind(id).first());}if(method==="DELETE"){await env.DB.prepare("DELETE FROM preconditions WHERE id=?").bind(id).run();return json({ok:true});}}
    if(url.pathname==="/api/test-sets"&&method==="GET")return json((await env.DB.prepare("SELECT s.*, (SELECT COUNT(*) FROM test_set_tests x WHERE x.test_set_id=s.id) test_count FROM test_sets s WHERE user_id=? ORDER BY updated_at DESC").bind(user.id).all()).results);
    if(url.pathname==="/api/test-sets"&&method==="POST"){const p=await body(req),id=uid(),at=iso(),key=String(p.key||"").trim().toUpperCase(),name=String(p.name||"").trim();if(!key||!name)return json({error:"Test-Set-Key und Name sind erforderlich"},400);await env.DB.prepare("INSERT INTO test_sets (id,user_id,set_key,name,description,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,user.id,key,name,p.description||"",p.status||"ACTIVE",at,at).run();return json(await env.DB.prepare("SELECT * FROM test_sets WHERE id=?").bind(id).first(),201);}
    if(parts[1]==="test-sets"&&parts[2]){const id=parts[2],set=await env.DB.prepare("SELECT * FROM test_sets WHERE id=? AND user_id=?").bind(id,user.id).first();if(!set)return json({error:"Test Set nicht gefunden"},404);if(parts[3]==="tests"&&(method==="POST"||method==="DELETE")){const p=await body(req),test=await env.DB.prepare("SELECT t.id FROM test_cases t JOIN releases r ON r.id=t.release_id WHERE t.id=? AND r.user_id=?").bind(p.testCaseId,user.id).first();if(!test)return json({error:"Testfall nicht gefunden"},404);if(method==="POST")await env.DB.prepare("INSERT OR IGNORE INTO test_set_tests (test_set_id,test_case_id,created_at) VALUES (?,?,?)").bind(id,test.id,iso()).run();else await env.DB.prepare("DELETE FROM test_set_tests WHERE test_set_id=? AND test_case_id=?").bind(id,test.id).run();return json({ok:true});}if(method==="GET"){const tests=(await env.DB.prepare("SELECT t.id,t.test_key,t.summary,t.local_status,r.name execution_name,r.execution_key FROM test_set_tests x JOIN test_cases t ON t.id=x.test_case_id JOIN releases r ON r.id=t.release_id WHERE x.test_set_id=? AND r.user_id=? ORDER BY t.test_key").bind(id,user.id).all()).results;return json({...set,tests});}if(method==="PATCH"){const p=await body(req);await env.DB.prepare("UPDATE test_sets SET set_key=?,name=?,description=?,status=?,updated_at=? WHERE id=?").bind(String(p.key??set.set_key).toUpperCase(),p.name??set.name,p.description??set.description,p.status??set.status,iso(),id).run();return json(await env.DB.prepare("SELECT * FROM test_sets WHERE id=?").bind(id).first());}if(method==="DELETE"){await env.DB.prepare("DELETE FROM test_sets WHERE id=?").bind(id).run();return json({ok:true});}}
    if(parts[1]==="tests"&&parts[2]&&parts[3]==="preconditions"&&(method==="POST"||method==="DELETE")){const test=await env.DB.prepare("SELECT t.id FROM test_cases t JOIN releases r ON r.id=t.release_id WHERE t.id=? AND r.user_id=?").bind(parts[2],user.id).first(),p=await body(req),pre=await env.DB.prepare("SELECT id FROM preconditions WHERE id=? AND user_id=?").bind(p.preconditionId,user.id).first();if(!test||!pre)return json({error:"Testfall oder Precondition nicht gefunden"},404);if(method==="POST")await env.DB.prepare("INSERT OR IGNORE INTO test_case_preconditions (test_case_id,precondition_id,created_at) VALUES (?,?,?)").bind(test.id,pre.id,iso()).run();else await env.DB.prepare("DELETE FROM test_case_preconditions WHERE test_case_id=? AND precondition_id=?").bind(test.id,pre.id).run();return json({ok:true});}
    if(url.pathname==="/api/plans"&&method==="GET")return json((await env.DB.prepare("SELECT p.*, (SELECT COUNT(*) FROM releases r WHERE r.plan_id=p.id) execution_count FROM test_plans p WHERE user_id=? ORDER BY updated_at DESC").bind(user.id).all()).results);
    if(url.pathname==="/api/plans"&&method==="POST"){const p=await body(req),id=uid(),at=iso(),key=String(p.key||"").trim().toUpperCase(),name=String(p.name||"").trim();if(!key||!name)return json({error:"Plan-Key und Name sind erforderlich"},400);await env.DB.prepare("INSERT INTO test_plans (id,user_id,plan_key,name,description,status,start_date,end_date,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(id,user.id,key,name,p.description||"",p.status||"DRAFT",p.startDate||"",p.endDate||"",at,at).run();return json(await env.DB.prepare("SELECT * FROM test_plans WHERE id=?").bind(id).first(),201);}
    if(parts[1]==="plans"&&parts[2]){const id=parts[2],plan=await env.DB.prepare("SELECT * FROM test_plans WHERE id=? AND user_id=?").bind(id,user.id).first();if(!plan)return json({error:"Testplan nicht gefunden"},404);if(method==="GET"){const executions=(await env.DB.prepare("SELECT *, (SELECT COUNT(*) FROM test_cases t WHERE t.release_id=releases.id) test_count FROM releases WHERE plan_id=? AND user_id=? ORDER BY updated_at DESC").bind(id,user.id).all()).results;return json({...plan,executions});}if(method==="PATCH"){const p=await body(req);await env.DB.prepare("UPDATE test_plans SET plan_key=?,name=?,description=?,status=?,start_date=?,end_date=?,updated_at=? WHERE id=?").bind(String(p.key??plan.plan_key).toUpperCase(),String(p.name??plan.name),String(p.description??plan.description),String(p.status??plan.status),String(p.startDate??plan.start_date),String(p.endDate??plan.end_date),iso(),id).run();return json(await env.DB.prepare("SELECT * FROM test_plans WHERE id=?").bind(id).first());}if(method==="DELETE"){await env.DB.prepare("UPDATE releases SET plan_id=NULL WHERE plan_id=?").bind(id).run();await env.DB.prepare("DELETE FROM test_plans WHERE id=?").bind(id).run();return json({ok:true});}}
    if(url.pathname==="/api/releases"&&method==="GET")return json((await env.DB.prepare("SELECT *, (SELECT COUNT(*) FROM test_cases t WHERE t.release_id=releases.id) test_count FROM releases WHERE user_id=? ORDER BY updated_at DESC").bind(user.id).all()).results);
    if(url.pathname==="/api/releases"&&method==="POST"){const p=await body(req),id=uid(),at=iso();await env.DB.prepare("INSERT INTO releases (id,name,execution_key,source_name,environment,created_at,updated_at,user_id) VALUES (?,?,?,?,?,?,?,?)").bind(id,String(p.name||"Release Test"),p.executionKey||"",p.sourceName||"",p.environment||"",at,at,user.id).run();return json(await getRelease(env.DB,id,user.id),201);}
    if(parts[1]==="releases"&&parts[2]){const id=parts[2],owned=await env.DB.prepare("SELECT id FROM releases WHERE id=? AND user_id=?").bind(id,user.id).first();if(!owned)return json({error:"Release nicht gefunden"},404);
      if(parts.length===3&&method==="GET"){const r=await getRelease(env.DB,id,user.id);return r?json(r):json({error:"Release nicht gefunden"},404);}
      if(parts.length===3&&method==="PATCH"){const p=await body(req),current=await env.DB.prepare("SELECT * FROM releases WHERE id=?").bind(id).first(),name=String(p.name??current.name).trim();if(!name)return json({error:"Release-Name ist erforderlich"},400);await env.DB.prepare("UPDATE releases SET name=?,execution_key=?,environment=?,description=?,revision=?,start_date=?,end_date=?,plan_id=?,updated_at=? WHERE id=?").bind(name,String(p.executionKey??current.execution_key),String(p.environment??current.environment),String(p.description??current.description),String(p.revision??current.revision),String(p.startDate??current.start_date),String(p.endDate??current.end_date),p.planId===undefined?current.plan_id:(p.planId||null),iso(),id).run();await audit(env.DB,id,null,"Release",current.name,name,"Release bearbeitet",user.display_name);return json(await getRelease(env.DB,id,user.id));}
      if(parts.length===3&&method==="DELETE"){await env.DB.prepare("DELETE FROM releases WHERE id=? AND user_id=?").bind(id,user.id).run();return json({ok:true});}
      if(parts[3]==="add-existing-tests"&&method==="POST"){const p=await body(req);return json(await addExistingTests(env.DB,user.id,id,p.testIds,user.display_name),201);}
      if(parts[3]==="tests"&&method==="POST"){const p=await body(req),key=String(p.key||p.testKey||"").trim().toUpperCase(),summary=String(p.summary||"").trim();if(!key||!summary)return json({error:"Test-Key und Zusammenfassung sind erforderlich"},400);if(await env.DB.prepare("SELECT id FROM test_cases WHERE release_id=? AND test_key=?").bind(id,key).first())return json({error:"Test-Key ist bereits vorhanden"},409);const tid=uid(),at=iso(),status=cleanStatus(p.status);await env.DB.prepare("INSERT INTO test_cases (id,release_id,test_key,summary,test_type,workflow_status,original_status,local_status,sync_status,tester,comment,actual_result,defect,updated_at,precondition,requirement_key,labels,component,priority,folder_path) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(tid,id,key,summary,p.testType||"Manual",p.workflowStatus||"READY",status,status,"UNCHANGED",p.tester||"",p.comment||"",p.actualResult||"",p.defect||"",at,p.precondition||"",p.requirementKey||"",p.labels||"",p.component||"",p.priority||"Medium",p.folderPath||"").run();for(const [i,s] of (p.steps||[]).entries())await env.DB.prepare("INSERT INTO test_steps (id,test_case_id,step_no,action,test_data,expected_result,actual_result,status,comment) VALUES (?,?,?,?,?,?,?,?,?)").bind(uid(),tid,i+1,s.action||"",s.data||"",s.expectedResult||"",s.actualResult||"",cleanStatus(s.status||"TO DO"),s.comment||"").run();await audit(env.DB,id,{id:tid,test_key:key},"Testfall","",summary,"Manuell erstellt",user.display_name);return json(await getRelease(env.DB,id,user.id),201);}
      if(parts[3]==="import"&&method==="POST")return importTests(env.DB,id,await body(req),user.id);
      if(parts[3]==="audit"&&method==="GET")return json((await env.DB.prepare("SELECT * FROM audit_log WHERE release_id=? ORDER BY created_at DESC LIMIT 1000").bind(id).all()).results);
      if(parts[3]==="tests"&&method==="DELETE"){await env.DB.batch([env.DB.prepare("DELETE FROM audit_log WHERE release_id=?").bind(id),env.DB.prepare("DELETE FROM test_steps WHERE test_case_id IN (SELECT id FROM test_cases WHERE release_id=?)").bind(id),env.DB.prepare("DELETE FROM test_cases WHERE release_id=?").bind(id)]);return json({ok:true});}
      if(parts[3]==="bulk-status"&&method==="PATCH"){const p=await body(req),status=cleanStatus(p.status),ids=Array.isArray(p.ids)?p.ids:[];for(const tid of ids){const t=await env.DB.prepare("SELECT * FROM test_cases WHERE id=? AND release_id=?").bind(tid,id).first();if(t&&t.local_status!==status){await env.DB.prepare("UPDATE test_cases SET local_status=?,sync_status='CHANGED',updated_at=? WHERE id=?").bind(status,iso(),tid).run();await audit(env.DB,id,t,"Status",t.local_status,status,"Sammeländerung",p.actor||"");}}return json(await getRelease(env.DB,id,user.id));}
      if(parts[3]==="reconcile"&&method==="POST"){const p=await body(req),remote=new Map((p.tests||[]).map(t=>[String(t.key||t.test_key),cleanStatus(t.status||t.local_status)]));const current=await getRelease(env.DB,id,user.id);let conflicts=0;for(const t of current.tests){if(!remote.has(t.test_key))continue;const rs=remote.get(t.test_key),localChanged=t.local_status!==t.original_status,remoteChanged=rs!==t.original_status;let local=t.local_status,original=t.original_status,sync=t.sync_status,remoteStatus=rs;if(localChanged&&remoteChanged&&local!==rs){sync="CONFLICT";conflicts++;}else if(!localChanged&&remoteChanged){local=original=rs;sync="UNCHANGED";}else if(localChanged&&local===rs){original=rs;sync="SYNCED";remoteStatus=null;}await env.DB.prepare("UPDATE test_cases SET local_status=?,original_status=?,remote_status=?,sync_status=?,updated_at=? WHERE id=?").bind(local,original,remoteStatus,sync,iso(),t.id).run();}return json({conflicts,release:await getRelease(env.DB,id,user.id)});}
    }
    if(parts[1]==="tests"&&parts[2]){const id=parts[2],t=await env.DB.prepare("SELECT t.* FROM test_cases t JOIN releases r ON r.id=t.release_id WHERE t.id=? AND r.user_id=?").bind(id,user.id).first();if(!t)return json({error:"Testfall nicht gefunden"},404);
      if(method==="PATCH"){const p=await body(req);if(p.resolve==="remote"&&t.remote_status){await env.DB.prepare("UPDATE test_cases SET original_status=?,local_status=?,remote_status=NULL,sync_status='SYNCED',updated_at=? WHERE id=?").bind(t.remote_status,t.remote_status,iso(),id).run();await audit(env.DB,t.release_id,t,"Konflikt",t.local_status,t.remote_status,"Xray übernommen",user.display_name);return json(await getRelease(env.DB,t.release_id,user.id));}if(p.resolve==="local"){await env.DB.prepare("UPDATE test_cases SET remote_status=NULL,sync_status='CHANGED',updated_at=? WHERE id=?").bind(iso(),id).run();await audit(env.DB,t.release_id,t,"Konflikt",t.remote_status,t.local_status,"Lokal behalten",user.display_name);return json(await getRelease(env.DB,t.release_id,user.id));}const allowed={status:"local_status",tester:"tester",comment:"comment",actualResult:"actual_result",defect:"defect",summary:"summary",workflowStatus:"workflow_status",testType:"test_type",precondition:"precondition",requirementKey:"requirement_key",labels:"labels",component:"component",priority:"priority",folderPath:"folder_path"};for(const [input,col] of Object.entries(allowed)){if(p[input]===undefined)continue;const value=input==="status"?cleanStatus(p[input]):String(p[input]??"");if(String(t[col]??"")===value)continue;await env.DB.prepare(`UPDATE test_cases SET ${col}=?,sync_status='CHANGED',updated_at=? WHERE id=?`).bind(value,iso(),id).run();await audit(env.DB,t.release_id,t,input,t[col],value,"",p.actor||"");t[col]=value;}return json(await getRelease(env.DB,t.release_id,user.id));}
      if(method==="DELETE"){await audit(env.DB,t.release_id,t,"Testfall","Vorhanden","Gelöscht");await env.DB.prepare("DELETE FROM test_cases WHERE id=?").bind(id).run();return json({ok:true});}
      if(parts[3]==="steps"&&method==="POST"){const p=await body(req),stepId=uid(),n=Number(p.stepNo||1);await env.DB.prepare("INSERT INTO test_steps (id,test_case_id,step_no,action,test_data,expected_result,actual_result) VALUES (?,?,?,?,?,?,?)").bind(stepId,id,n,p.action||"",p.data||"",p.expectedResult||"",p.actualResult||"").run();await audit(env.DB,t.release_id,t,`Schritt ${n}`,"","Erstellt");return json(await getRelease(env.DB,t.release_id,user.id),201);}
    }
    if(parts[1]==="steps"&&parts[2]){const id=parts[2],s=await env.DB.prepare("SELECT s.*,t.release_id,t.test_key FROM test_steps s JOIN test_cases t ON t.id=s.test_case_id JOIN releases r ON r.id=t.release_id WHERE s.id=? AND r.user_id=?").bind(id,user.id).first();if(!s)return json({error:"Schritt nicht gefunden"},404);if(method==="PATCH"){const p=await body(req),allowed={action:"action",data:"test_data",expectedResult:"expected_result",actualResult:"actual_result",status:"status",comment:"comment"};for(const [input,col] of Object.entries(allowed))if(p[input]!==undefined)await env.DB.prepare(`UPDATE test_steps SET ${col}=? WHERE id=?`).bind(String(p[input]??""),id).run();await audit(env.DB,s.release_id,{id:s.test_case_id,test_key:s.test_key},`Schritt ${s.step_no}`,"","Bearbeitet");return json({ok:true});}if(method==="DELETE"){await env.DB.prepare("DELETE FROM test_steps WHERE id=?").bind(id).run();await audit(env.DB,s.release_id,{id:s.test_case_id,test_key:s.test_key},`Schritt ${s.step_no}`,"Vorhanden","Gelöscht");return json({ok:true});}}
    if(url.pathname==="/api/defects"&&method==="POST"){const p=await body(req),t=await env.DB.prepare("SELECT t.* FROM test_cases t JOIN releases r ON r.id=t.release_id WHERE t.id=? AND r.user_id=?").bind(p.testCaseId,user.id).first();if(!t)return json({error:"Testfall nicht gefunden"},404);const id=uid(),at=iso(),key=String(p.key||"LOCAL-"+Date.now()).trim().toUpperCase(),summary=String(p.summary||"").trim();if(!summary)return json({error:"Bug-Zusammenfassung ist erforderlich"},400);await env.DB.prepare("INSERT INTO defects (id,user_id,release_id,test_case_id,test_step_id,defect_key,summary,description,severity,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,user.id,t.release_id,t.id,p.testStepId||null,key,summary,p.description||"",p.severity||"Major",p.status||"OPEN",at,at).run();await audit(env.DB,t.release_id,t,"Defect","",key+" "+summary,"Bug erfasst",user.display_name);return json(await getRelease(env.DB,t.release_id,user.id),201);}
    if(parts[1]==="defects"&&parts[2]){const id=parts[2],d=await env.DB.prepare("SELECT * FROM defects WHERE id=? AND user_id=?").bind(id,user.id).first();if(!d)return json({error:"Defect nicht gefunden"},404);if(method==="PATCH"){const p=await body(req);await env.DB.prepare("UPDATE defects SET defect_key=?,summary=?,description=?,severity=?,status=?,updated_at=? WHERE id=?").bind(String(p.key??d.defect_key),String(p.summary??d.summary),String(p.description??d.description),String(p.severity??d.severity),String(p.status??d.status),iso(),id).run();return json(await getRelease(env.DB,d.release_id,user.id));}if(method==="DELETE"){await env.DB.prepare("DELETE FROM defects WHERE id=?").bind(id).run();return json(await getRelease(env.DB,d.release_id,user.id));}}
    if(url.pathname==="/api/evidence"&&method==="POST"){const p=await body(req),t=await env.DB.prepare("SELECT t.* FROM test_cases t JOIN releases r ON r.id=t.release_id WHERE t.id=? AND r.user_id=?").bind(p.testCaseId,user.id).first();if(!t)return json({error:"Testfall nicht gefunden"},404);const mime=String(p.mimeType||"");if(!mime.startsWith("image/"))return json({error:"Nur Bilddateien sind erlaubt"},400);const data=String(p.dataBase64||"").replace(/^data:[^;]+;base64,/,""),size=Math.ceil(data.length*0.75);if(!data||size>750000)return json({error:"Bild fehlt oder ist größer als 750 KB"},400);const id=uid();await env.DB.prepare("INSERT INTO evidence (id,user_id,release_id,test_case_id,test_step_id,file_name,mime_type,file_size,data_base64,note,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id,user.id,t.release_id,t.id,p.testStepId||null,String(p.fileName||"Nachweis"),mime,size,data,String(p.note||""),iso()).run();await audit(env.DB,t.release_id,t,"Bildnachweis","",p.fileName||"Bild","Evidence hinzugefügt",user.display_name);return json(await getRelease(env.DB,t.release_id,user.id),201);}
    if(parts[1]==="evidence"&&parts[2]){const id=parts[2],e=await env.DB.prepare("SELECT * FROM evidence WHERE id=? AND user_id=?").bind(id,user.id).first();if(!e)return json({error:"Nachweis nicht gefunden"},404);if(method==="GET")return new Response(Uint8Array.from(atob(e.data_base64),x=>x.charCodeAt(0)),{headers:{"content-type":e.mime_type,"cache-control":"private,max-age=3600"}});if(method==="DELETE"){await env.DB.prepare("DELETE FROM evidence WHERE id=?").bind(id).run();return json(await getRelease(env.DB,e.release_id,user.id));}}
    return json({error:"Route nicht gefunden"},404);
  }catch(error){return json({error:error.message||"Serverfehler"},400);}
}
export default {async fetch(req,env){const url=new URL(req.url);if(url.pathname.startsWith("/api/"))return api(req,env);return env.ASSETS.fetch(req);}};
